name: quizzical
description: A fun spinner quiz app for the web.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.7+7

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensures compatibility with the latest Dart SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  flutter_fortune_wheel: ^1.3.0 # For a more advanced spinner
  google_fonts: ^6.2.1 # Add this for custom fonts
  confetti: ^0.7.0 # Add this for confetti animation
  audioplayers: ^5.2.0
  vibration: ^1.7.7
  google_nav_bar: ^5.0.6
  flutter_animate: ^4.2.0
  #flutter_vibrate:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
  # To add assets like images or fonts:
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: Pacifico
  #     fonts:
  #       - asset: fonts/Pacifico-Regular.ttf