name: quizzical
description: Your Fun Study Tool.
publish_to: 'none'

version: 2.4.9+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  flutter_fortune_wheel: ^1.3.0
  google_fonts: ^6.2.1
  confetti: ^0.7.0
  audioplayers: ^5.2.0
  vibration: ^1.7.7
  google_nav_bar: ^5.0.6
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/app_icon_foreground.png # Make sure you list your foreground image in assets

# Flutter Launcher Icons configuration for ADAPTIVE ICONS
# flutter pub run flutter_launcher_icons:main
flutter_launcher_icons:
  android: true # This tells the package to generate Android icons.
  ios: true # Set to true if you also want to generate regular iOS icons.
  image_path: "assets/app_icon.png" # This is a fallback/default for non-adaptive contexts (like iOS) or older Android versions.
  # You can point it to a combined version of your logo or the foreground.
  adaptive_icon_background: "#F8F0E5" # Replace with your desired background color (e.g., white, blue, etc.)
  adaptive_icon_foreground: "assets/app_icon_foreground.png" # Path to your transparent foreground image.
  # Optional: For Web platform
  web:
    generate: true
    image_path: "assets/app_icon_foreground.png" # Use your foreground for web
    background_color: "#F8F0E5" # Match your adaptive background color
    theme_color: "#F8F0E5" # Match your adaptive background color